### ISSUE TITLE
Missing mechanism to rotate keys in the cluster

### ISSUE THREAD

**Issue by ahawtho** [bitnami-labs/sealed-secrets#108] opened 2018-07-23 22:08 UTC
I don't see it in the documentation: is there a way to rotate keys in the cluster, so that more than one keypair is supported simultaneously? By the encoding being used in the secret, it doesn't seem like it's possible.

It should be possible to rotate keys, supporting multiple keys, potentially flagging Secret objects that are using an "old" key so they can be updated to a newer key. Having an expiration period, and metrics exposed for number of secret objects using old key(s) and time left for a key to expire would also be helpful to make it possible to alert based on expiring keys, similar to a capacity alert for storage.

**Comment by anguslees** [comment] 2018-07-24 00:39
There is not currently a way to rotate keys (other than a naive and disruptive key replacement).  I agree this is a highly desirable feature.

My intention was to extend the controller to read a list of multiple Secrets, and try each for decryption. I like your suggestions for exposing additional metrics/debugging too.

**Comment by caiobegotti** [comment] 2019-06-25 16:30
I know this could in the roadmap eventually but what would be the recommended way from you guys about that in a way that is "Seal Secrets-tonic" until such feature exists? Like, manually do that decryption checks and replace each one manually?

**Comment by mkmik** [comment] 2019-07-26 09:37
Closing as duplicate of #137

**Closed by mkmik** 2019-07-26 09:37 UTC
Labels: enhancement, good first issue
