### ISSUE TITLE
Document Cluster wide secret usage

### ISSUE THREAD

**Issue by deyceg** [bitnami-labs/sealed-secrets#107] opened 2018-07-21 08:05 UTC
Any chance of some improved documentation or an example? It's not really clear to me how this is supposed to work...

Does the annotation go on the unencrypted or encrypted secret?
How does the controller propagate the secret to other namespaces in the cluster?

I can see you guys have an integration test for it, but I haven't been able to get it working in my cluster.

**Comment by deyceg** [comment] 2018-07-24 10:17
@anguslees any love?

**Comment by mkmik** [comment] 2019-09-13 15:48
thanks @linuxbsdfreak . I'd like to improve the documentation on this.

The annotation goes on both the secret you pass as input to `kubeseal` and it will be included in the generated sealed secret (so that we know how to decrypt it, as non cluster-wide secrets literally include the namespace and secret name in the encryption key)

**Comment by mkmik** [comment] 2019-09-13 16:35
Duplicate of #241

**Closed by mkmik** 2019-09-13 16:35 UTC
