### ISSUE TITLE
kubeseal should not require a `~/.kube/config`

### ISSUE THREAD

**Issue by bremnes** [bitnami-labs/sealed-secrets#101] opened 2018-05-14 13:23 UTC
Love the idea of this project, but I encountered a (user?) problem of a non-responsive terminal. On ubuntu with the v0.7.0 kubeseal-linux-amd64.

Documentation:
>...
> \# This is the important bit:
> $ kubeseal <mysecret.json >mysealedsecret.json
>...

I'm trying to do this offline so I've saved the public key as a pem file.
```
kubeseal <secret.json >mysealedsecret.json --cert test.pem
panic: invalid configuration: no configuration has been provided
```

Figuring that the '<' before secret.json might not belong there(?):
```
kubeseal secret.json >mysealedsecret.json --cert test.pem
```

This leads to kubeseal not returning anything, just seemingly working in the background. I can type more text, but it doesn't do anything so I just have to close the process. `mysealedsecret.json` is created, but the size is 0 bytes. (I also tried `kubeseal secret.json mysealedsecret.json --cert test.pem` with the same result.)

What am I missing here?

**Comment by c-knowles** [comment] 2018-05-14 13:27
Does `kubeseal --cert test.pem <secret.json >mysealedsecret.json` work? Might be something with how the flags are parsed.

**Comment by c-knowles** [comment] 2018-05-14 13:53
Running in a container like that shouldn't matter. We're using pretty much the same command although running it on mac OS.

I had a quick look around for similar issues, it appears like the calls out the k8s go SDK are looking for `~/.kube/config` and this is the error throw if it does not exist. Would you mind trying to create that file? Maybe empty first and if they doesn't work it might need to be a valid format. Note, it appears the current code for sealed secrets defaults to the namespace from the current kube config if not specified in the secret so ensure you set that as well.

Probably sealed secrets could support an offline mode including missing kube config file.

**Comment by bremnes** [comment] 2018-05-14 15:13
This is on a non-kubernetes/kubelet client machine, so there was no kube config present. I thought it would be possible, because we are looking into using this in our ci/cd pipeline which doesn't necessarily have any connection to Kubernetes if we go for a cluster-pull type of deployment architecture.

First I tried with an empty file, but I still got the `no configuration provided` error.

Then I tried experimenting with the config file, and it's not much information that is needed there. I just took my local docker-for-windows config and stripped out the user/certificate parts. In fact I don't quite see the reason for having it, and I think there's potential for streamlining the offline experience.

```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:6445
  name: docker-for-desktop-cluster
contexts:
- context:
    cluster: docker-for-desktop-cluster
    user: docker-for-desktop
  name: docker-for-desktop
current-context: docker-for-desktop
kind: Config
```

Anyways, thanks for the help @c-knowles :) I'll guess if we are to use sealed secrets we'll just add a dummy configuration file to the repository and point the `--kubeconfig` towards it.

**Comment by c-knowles** [comment] 2018-05-14 16:02
I think this could be changed to streamline it as you say. Should be quite easy to wrap the code that setups that up a little more.

**Comment by c-knowles** [comment] 2018-05-14 16:18
@bremnes out of interest, what’s the use case to use the kubeseal CLI inside the CI? When commiting a sealed secret, I believe a typical setup means the CI never has access to the decrypted version since it never needs to. So I’m wondering what exactly causes your case to need kubeseal within the CI.

**Comment by bremnes** [comment] 2018-05-15 13:52
We haven't commited to the GitOps route yet, but we are looking into it. There are some details that I don't quite see how are being solved, so I might be misinterpreting the whole thing.

For instance if I have this hello-world application without any environment variables (secrets). Then I would have a deployment manifest or helm chart in my source repo which when GitOpsed is pull requested/checked into my infrastructure-qa/prod repository (?).

The missing step I don't see here is if I want to add for instance a database to this application. I would need secret(s), typically in a secret.json or similar. In my source repository I'd have one secrets.json file (tokenized?) and no reference to environment(s). But through the GitOps cycle those secrets needs to be fetched/generated and then pull requested/checked into the infrastructure-qa/prod/whatever repo. (Or are you expected to manually generate the secrets.json in each infrastructure repository?)

That's why I saw one use case of being 
CI: build docker image; push that image to docker repo; insert image version into deployment.yaml; send deployment.yaml, secret.yaml (tokenized), configmap.yaml (tokenized)
CD alternative a: get environment values/secrets; encrypt secrets using kubeseal & base64 and replace tokens in secret.yaml; replace tokens in configmap.yaml; check into the correct environment/infrastructure repository. Then have a separate component apply those manifests/charts such as landscaper or flux. When promoting in the CD tool the respective infrastructure repo would get the "correct" manifests/helm charts.
CD alternative b (the old way): get environment values/secrets; base64 encode secrets into secret.yaml; replaces tokens in configmap.yaml; apply to environment.

Like I said, there's something I'm not seeing here. All the articles and videos I've seen seems to be skipping that part. Feel free to enlighten me :)

Another use case is obviously if that those sealed secrets need to be manually checked in "by hand" it might be that the person doing that doesn't have a kubernetes/kubectl connection set up. Because of the whole "kubectl is the new ssh" thing, even though I know that is a bit far fetched as the people knowing of the sensitive password probably would be ops/dev people being very hands-on.

**Comment by anguslees** [comment] 2018-05-16 03:05
> I'll guess if we are to use sealed secrets we'll just add a dummy configuration file to the repository and point the --kubeconfig towards it.

Yep, that's the bug here: `kubeseal` is _supposed_ to be able to be used (with `--cert`) without access to a cluster, but the way I'm initialising the client-go library apparently still requires a dummy `~/.kube/config` file or it throws an error.  The error message could also do with some additional context to make that correlation clearer.

> Figuring that the '<' before secret.json might not belong there(?)
> This leads to kubeseal not returning anything,

That's correct.  `kubseal` reads its input "secret" from stdin, which is what the `< secret.json` normally provides.  If you remove the `<` then you're telling your shell to use the regular console input as stdin - as in `kubeseal` is now "hanging" waiting for you to hand type in a secret and hit ^d (usual shell EOF).  Again, this is your *shell* not `kubeseal` itself.

I could change `kubseal` to perform in a different way, but this is normal unix shell tool behaviour, so I feel I'd just be swapping one set of UX expectations for another ...
We _do_ need to rethink the way `kubeseal` is used now that we have individually encrypted values, so I'll be sure to include your (poor) experience here as part of that rethink.

> out of interest, what’s the use case to use the kubeseal CLI inside the CI?

Fwiw, I always imagined one of the use cases for `kubeseal` to be a CI bot that regenerates secrets every (eg) few weeks and automatically proposes/merges a PR with the new sealed secrets.  I hoped the "one way" nature of sealed secrets encryption would _encourage_ frequent and automatic password rotation, and "just regenerate" as a preferable alternative to storing a copy of the plaintext.

Retitling/reopening to make `kubeseal --cert` just-work without a `~/.kube/config`

**Comment by c-knowles** [comment] 2018-05-20 16:19
I think most of our stuff has the sealed secrets as part of the helm chart for the app, with environment selection where necessary, no separate repo. Secret rotation is an interesting case for sure, I'd be interested to have something more automatic in place if the source system supports it - ours are mainly DBs like RDS and some third party providers which would be tricker to automate.

**Comment by Docteur-RS** [comment] 2019-01-03 15:01
Got a similar problem while trying the command provided in the Readme.
`kubeseal <mysecret.json >mysealedsecret.json`

I didn't have any ~/.kube/config file either so I copied the one from kubernetes.

`sudo cp /etc/kubernetes/admin.conf ~/.kube/config` and then removed root ownership with "sudo chown user:group ~/.kube/config".
For instance if your user is vagrant you can try `sudo chown vagrant:vagrant ~/.kube/config`

**Comment by kskewes** [comment] 2019-02-04 00:52
I have just tried reproducing this with a build from master using an Alpine container but was unable to. Maybe fixed?

For reference, commands used:
```
# dist/linux_amd64/kubeseal --version
kubeseal version: a31f1ee3da9c5972fd865761910e3876e665e17b

# kubeseal --cert sealed-secrets-public.cert
<input k8s secret>
<ctrl+d>
<sealed-secret json output>
```

**Comment by diist** [comment] 2019-02-27 04:56
If that's fixed on master could we get a new release? There has been no release in almost a year, `v0.7.0` doesn't even have the `--version` command added 10 months ago 😢

**Comment by YGwen** [comment] 2019-06-19 16:25
Any update on this ?

**Comment by mkmik** [comment] 2019-07-29 12:06
I just tested this on `v0.8.x`, it works. Closing

**Comment by mauro0x52** [comment] 2019-08-12 18:28
I'm still having troubles with `--cert`.

See my logs:
```
$ kubeseal --version
kubeseal version: v0.8.1

$ kubeseal --cert alpha.pem --format yaml <secret.yaml >sealed-secret.yaml 
panic: invalid configuration: no configuration has been provided

goroutine 1 [running]:
main.main()
	/home/travis/gopath/src/github.com/bitnami-labs/sealed-secrets/cmd/kubeseal/main.go:357 +0x50c
```

It works fine if  I have my config set to our alpha or production environments. But with Minikube, it throws this error.

**Comment by rwhaling** [comment] 2019-11-12 21:01
Just a heads up - I can also report that running `kubeseal --cert` with no kubeconfig available bombs out with `invalid configuration: no configuration has been provided`

This is impactful, because we'd like for devs who do not have kubectl or cluster access to be able to seal secrets; any chance of re-opening this issue?

**Comment by mkmik** [comment] 2019-11-13 07:19
Uh, if it still doesn't work, we should reopen the issue indeed. @rwhaling your `kubeseal --version` ?

**Comment by mkmik** [comment] 2019-11-13 12:18
Sealed-secrets need to know the namespace of the secret it's sealing.
It can get the namespace in 3 ways (in order of precedence)

1. from the `-n`|`--namespace` flag.
2. from the input secret's metadata.
3. from the kubeconfig file.

We have bug in the way we report the condition when none of those 3 sources is available.
Will track in #313.

**Closed by mkmik** 2019-11-13 12:18 UTC
Labels: bug

**Comment by mallikarjunraju** [comment] 2021-08-19 18:20
for users with k3s installed, run `export KUBECONFIG=/etc/rancher/k3s/k3s.yaml`
