### ISSUE TITLE
armv7 release is in the wrong binary format

### ISSUE THREAD

**Issue by pisymbol** [bitnami-labs/sealed-secrets#354] opened 2020-02-13 03:33 UTC
Downloaed the 0.97 kubeseal-arm binary and when I run it on my RPi 4:

```
pi@pimaster:~ $ ./kubeseal-arm
-bash: ./kubeseal-arm: cannot execute binary file: Exec format error
pi@pimaster:~ $ file  ./kubeseal-arm
./kubeseal-arm: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
pi@pimaster:~ $
```

I was expecting an ARM ELF.

Is this just a build/release issue?

**Comment by mkmik** [comment] 2020-02-25 15:59
sorry only noticed now that we already had this issue filed. Duplicate of #362 (fixed)

**Closed** 2020-02-25 15:59 UTC
