### ISSUE TITLE
Support docker-registry secret type

### ISSUE THREAD

**Issue by brantb** [bitnami-labs/sealed-secrets#86] opened 2018-04-09 20:57 UTC
I'm trying to seal a docker registry secret, but when the controller unseals the secret it is always of `type: Opaque`.

Sample:
```
$ kubectl create secret docker-registry my-registry \
  --docker-server=myserver.example.com \
  --docker-username=user \
  --docker-password=password \
  --docker-email=fake@example.com \
  --output json --dry-run | kubeseal > sealed.json
$ kubectl apply -f sealed.json
$ kubectl get secret my-registry -o yaml
```
```yaml
apiVersion: v1
data:
  .dockerconfigjson: [snip]
kind: Secret
metadata:
  creationTimestamp: 2018-04-09T20:52:03Z
  name: my-registry
  namespace: default
  ownerReferences:
  - apiVersion: bitnami.com/v1alpha1
    controller: true
    kind: SealedSecret
    name: my-registry
    uid: db17d8cf-3c37-11e8-98fb-0a58ac1f010d
  resourceVersion: "3425531"
  selfLink: /api/v1/namespaces/default/secrets/my-registry
  uid: db1c68ac-3c37-11e8-98fb-0a58ac1f010d
type: Opaque
```

Expected result: The secret's `type` is `kubernetes.io/dockerconfigjson`.

Actual result: The secret type is `Opaque`.

**Comment by linoplt** [comment] 2018-04-18 15:16
@brantb You are able to seal docker-registry type secrets with v0.5.1. Haven't checked v0.6.0.

**Comment by jkinred** [comment] 2018-07-09 05:07
Any chance we can get a release cut with the fix for this one?

We are running off `quay.io/bitnami/sealed-secrets-controller:latest` which feels a bit precarious.

**Comment by pst** [comment] 2018-09-15 11:43
This bug still affects version 0.7.0 so I would suggest to re-open this issue. Status closed, a merged PR and the fact that this is many months old is just wasting everyone's time. Make it clear that this is broken.

A workaround is to seal a `type: kubernetes.io/dockerconfigjson` secret with 0.5.1. The newer controllers unseal it just fine.

**Comment by anguslees** [comment] 2018-09-17 07:16
@pst is perfectly correct. Reopening until a new release is made.  (If only github supported some sort of "Fixes" feature across more of the release cycle workflow...)

**Comment by colt-jay** [comment] 2018-11-07 15:28
Confirmed the solution of reverting kubeseal to 0.5.1 to seal a docker secret works.

We also ran into this issue. Would be great if it could be addressed in the next release :)

**Comment by linuxbsdfreak** [comment] 2018-12-05 08:44
Hi @anguslees @brantb @colt-jay  ,

I am performing the following steps based on https://github.com/stefanprodan/gitops-helm#managing-kubernetes-secrets:

- kubeseal --fetch-cert \
--controller-namespace=adm \
--controller-name=sealed-secrets \
> pub-cert.pem

- kubectl -n dev create secret docker-registry image-pull-secret-2 --docker-server=dockerrepo.mydomain.com --docker-username=xxxxxx --docker-password="xxxxx" --docker-email="test@mydomain.com" --dry-run -o json > image-pull-secret-2.json

- kubeseal --format=yaml --cert=pub-cert.pem <  image-pull-secret-2.json >  image-pull-secret-2.yaml

-  cat image-pull-secret-2.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-pull-secret-2
  namespace: dev
spec:
  data: AgDTiRafm0jOQKn/57QHdHh6Ocb/xex4/rSBQ2+HVUiN5mAFSam9g7JWulnp7l3WxjrSxWYe9buNEmZjpIqPLg2lyM7rMRlfE1br/wTd14GE5Di9YF4VXBqufaUVgmTehcJKD3+rtdP04+cfweRuESWF/A2/xR2W1kQ0aZDdYYNHVzcfVKpGGMFsgW+0q/7E5wsgfqTbC42vF+Q4ni/P1MfjZzxVcs4+b7pfW+jZbAXkodKCMegRuCXsUdVp5rC0fNruRZxA4d5blCDy1+4IsfQS1nn4c1OWOZgWJTKadG5k3uTHvTRcVxCM3ku7o4KSVoS0Q1/9EXAvszzyu7cIIbFZmPqq3eO3uLNkbJ5dyDOX+TkRSOW7Jtkm5VH+M1CXTLx90UPc/KEGznW9wulhC5eLFWG6qpk6k0Of56jkwJ19Tm9PJuUkIjIcpFvbBgmPADg8xbOkO6/VuU2O7V9IHSkumxN6Wu6yuYi0uDfEWVh/w8AyjE7sA1ZTuW3JTHju0RsPY6w/3oqiUZA9AWIo9PY/CogGmlFXXsHEl3MTw8ehrWmCXyrk6PoCSWWENUXoEYO716XN7K0pgzGk/xfEKNys18NH4oxAwLvJ1iQ3LKdFOPoMa1/NIi1jbYcu9b1GTTsdC7kIoQZMgNGFqKjb0Oxa1HIkvRUtKrRGxXyPEx3Ab+TbmYICuxsZye+HKvhlfmj3okGeobAFQwobPX5Ozm/hECCocIomjS7o4/1aZdxcmhdFMs3W1dj1g6IWLOfcMwbCC5gHVd9Nq3ThFEx3Sdf45jecHyxR79h9zXsaUzEOQLOwc1lEb/bE/S9P+Z00l7XjmlkHFmn+i0INN41Nj2F/2YGDSAKr9wk7m5aC8N/dQRxW4sRkCDkMLD2GznNcQk7Npr5mKKoEC4jtb7S2715SWHQojsUY3B7uqwjDIFFx+oWBIpXskhaiimysvodRRMuFhHQAa7k9VZfRIsiUtK6X5RmPDAZzkPYNxMo9a3JefsYfx0YK81RkTLZSgLFuZNHZOP7SBJKorYQpcBkVSbEgCyYT4yBLynUrbaRoMTAEZbwBlYyYYoPAXl2LcBCYpsUcAqJUAf9OSRmwUmebhMGJtYcZcP5kji32Sj28zy8fVDtD6zcGzA729cR4e1eKLjcRn1N9tXu05cYCK2jDmAlUwI9yedkkktLEVl3/j61lBZxdAm1qPzPVoWWqjfNP8APgfu6F2qIXjxfuPhMfQ2bM3AzycevimfNmwA+2KOfN3IZJ60kjaNvdpswsO7hCl52P4Z5STTn9obybdDPO4sO/pKM1E/9ad1TBKd121eWBe+0MZ2/jBhjogA==

- Committed the pub-cert.pem and the image-pull-secret-2.yaml to /releases/dev/ and pushed it to the repo. 

I also used the image: quay.io/bitnami/sealed-secrets-controller:v0.5.1 and image: quay.io/bitnami/sealed-secrets-controller:latest and used kubseal v0.5.1 to seal but i get the following error in the controller logs of the pod. 

2018/12/05 08:29:00 Updating dev/image-pull-secret-2
2018/12/05 08:29:00 Error updating dev/image-pull-secret-2, giving up: Secret "image-pull-secret-2" is invalid: type: Invalid value: "kubernetes.io/dockerconfigjson": field is immutable
E1205 08:29:00.246197       1 controller.go:162] Secret "image-pull-secret-2" is invalid: type: Invalid value: "kubernetes.io/dockerconfigjson": field is immutable

What am i doing wrong?

Regards,
Kevin

**Comment by linuxbsdfreak** [comment] 2018-12-05 12:49
Yes i am using the latest controller and the kubeseal only works with v0.5.1 for docker registry config

**Comment by spommerening** [comment] 2019-01-29 13:11
Hmmmm, is there any way to find out which version of `kubeseal` I installed locally? 
There seems to be no `--version` option for kubeseal or what am I doing wrong?

**Comment by kskewes** [comment] 2019-02-02 23:52
@spommerening - current master has `--version` if you build it. Older releases don't have version flag.
You could re-download whichever version(s) you require.

**Comment by eimarfandino** [comment] 2019-03-01 12:45
are you guys planning to resolve this soon in a future release?

**Comment by kraney** [comment] 2019-03-27 23:03
The suggested workaround does not work for me, with a 0.7.0 controller . I get this error in the logs:

Secret "artifactory-docker-secret" is invalid: type: Invalid value: "kubernetes.io/dockerconfigjson": field is immutable

**Comment by kraney** [comment] 2019-03-27 23:05
Never mind, deleting the sealedsecret and recreating it resolved the issue. (As compared to updating it.)

**Comment by radityasurya** [comment] 2019-03-28 09:40
@kraney is it changing the type to Opaque or keeping the type to kubernetes.io/dockerconfigjson

**Comment by kraney** [comment] 2019-03-28 14:01
So with 0.7.0 secrets were transmuted from docker to Opaque.

After reading the workaround above I recreated the sealedsecret using 0.5.1. I’m using flux so I checked this in. Flux then applied the change as an update.

This resulted in the error you see above. Seemingly, sealedsecrets attempted to make the change as an update but since the ‘type’ field is immutable, this failed.

I then manually deleted the sealedsecret. A few minutes later flux put it back, this time as a create. Sealedsecrets did a corresponding create and everything started working.

It’s conceivably a separate bug that sealedsecrets attempts to apply a type change as an update. I don’t know if that’s something you’d hit, though, in absence of this bug. I supposed you might if a user made a mistake and then tried to correct it.

**Comment by kraney** [comment] 2019-03-28 14:07
One other thing I’d like to add is that IMO this bug should be considered higher priority than it seems to be getting. Even though there’s a workaround, it causes some pretty obtuse failures that can be quite hard to debug.

In my case, diagnosis was from an error message that a particular docker image wasn’t found. Not that there was a login failure with the registry, certainly not that the imagePullSecret was invalid. So this launched a long diagnosis.

It took a long time to notice that the secret that was correctly there and had the right data had the wrong _type_. The user experience of it is pretty bad.

**Comment by radityasurya** [comment] 2019-03-28 14:11
Same thing, I reseal the secret with 0.5.1 and it works again, but the structure is really different.

**Comment by primeroz** [comment] 2019-04-05 13:47
+1 for higher priority for this bug.

I keep hitting it for almost every use of sealed secrets

**Comment by JaimsDC** [comment] 2019-05-21 09:52
Yep it's been over a year :(

**Comment by jaygorrell** [comment] 2019-05-31 22:22
Ugh, also just ran into this but I see it's been a long time. Is this project still active?

**Comment by jaygorrell** [comment] 2019-05-31 22:26
Just found the discussion in https://github.com/bitnami-labs/sealed-secrets/issues/165 that may be of interest to everyone on this issue.

**Comment by Bronek** [comment] 2019-07-10 17:38
According to https://github.com/bitnami-labs/sealed-secrets/pull/170#issuecomment-509871583 this is now solved by #180

**Comment by demisx** [comment] 2019-07-17 03:31
It is indeed fixed on  latest `master`.  However, I had to manually edit the generated `controller.yaml` to change from:

```yml
image: sealed-secrets-controller:latest
```

to 

```yml
image: quay.io/bitnami/sealed-secrets-controller:latest
```

so it doesn't try to pull the image from the Docker Hub. Is there a way to do generate `controller.yaml` with the correct image URL already in place?

**Comment by mkmik** [comment] 2019-07-17 06:49
The CI run (see `.travis.yml`) sets the release image-name in `CONTROLLER_IMAGE` makefile variable. You can do it manually with:

```
$ make CONTROLLER_IMAGE=quay.io/bitnami/sealed-secrets-controller:latest controller.yaml
```

**Comment by mkmik** [comment] 2019-07-17 06:50
Closing as the issue is now fixed; will make a new release soon

**Closed by mkmik** 2019-07-17 06:50 UTC
Labels: bug

**Comment by demisx** [comment] 2019-07-18 16:00
@mkmik Is there any way to install the latest master with the Helm chart? I'd like to deploy the fix to our cluster before the new release is published. Thank you very much.

**Comment by mkmik** [comment] 2019-07-18 17:56
The helm chart is community supported.
Sealed-secrets can be deployed with a simple yaml or with kubecfg. Do you have any specific features from the helm chart that you depend on?

On Thu, Jul 18, 2019, 18:00 Dmitri Moore <notifications@github.com<mailto:notifications@github.com>> wrote:

@mkmik<https://github.com/mkmik> Is there any way to install the latest master with the Helm chart? I'd like to deploy the fix to our cluster before the new release is published. Thank you very much.

**Comment by demisx** [comment] 2019-07-18 21:15
I'd just like to be able to bootstrap the cluster consistently using helm charts. I see there is [one here for sealed secrets](https://github.com/helm/charts/tree/master/stable/sealed-secrets), but it currently [points to v0.7](https://github.com/helm/charts/blob/master/stable/sealed-secrets/values.yaml#L3) by default. I need to install what's the latest on master, because it fixes this bug. Is it just a matter of setting the image tag to `latest`? 

```ts
helm install \
  --namespace kube-system \
  --name sealedsecrets \
  --set image.tag=latest \
  stable/sealed-secrets 
```

Sorry, if this is a dumb question - I am just starting to learn helm:

**Comment by demisx** [comment] 2019-07-18 23:04
FYI, when I tried it with `--set image.tag=latest`, the container fails to start. I see this:

```
Successfully assigned kube-system/sealedsecrets-sealed-secrets-568b4f785d-9t26j to ip-17...
Container image "quay.io/bitnami/sealed-secrets-controller:latest" already present on machine
Created container
Started container
Back-off restarting failed container
```

Is setting the `image.tag` not enough?

**Comment by mkmik** [comment] 2019-07-19 10:30
The new controller.yaml file has changed quite a bit.
We'll do soon another release.

I assume the helm chart maintainer cannot update the chart until we cut a new release.

**Comment by demisx** [comment] 2019-07-19 13:41
@mkmik Thank you. That would be awesome! Many are so desperately waiting for `v0.8.0`. I will help with the chart release update, if needed, as well. This is such an excellent product and we are very happy to see it gaining some traction again.

**Comment by mkmik** [comment] 2019-07-25 15:56
@demisx FWIW the helm chart for v0.8.0 has been released (https://github.com/helm/charts/pull/15800)

**Comment by muhlba91** [comment] 2019-07-25 18:55
I have tried using the chart including RBAC and received a startup error that the serviceaccount is not allowed to list secrets in the namespace the controller is deployed.

Is this an error in the helm chart RBAC with missing list permissions or an issue with the controller?

**Comment by mkmik** [comment] 2019-07-25 19:23
@muhlba91 
see https://github.com/helm/charts/issues/15837

The helm chart hasn't been updated with the new yaml
