### ISSUE TITLE
Add/restore openapi schema for CRD

### ISSUE THREAD

**Issue by anguslees** [bitnami-labs/sealed-secrets#82] opened 2018-03-05 02:40 UTC
See discussion during PR #73.  We had to remove the schema due to upstream k8s limitations that left us with no option to keep the schema _and_ allow an object with arbitrary keys.  This issue is to track finding a workaround and/or upstream fix that allows us to have key/value objects _and_ a CRD schema.

**Comment by smoyer64** [comment] 2022-02-03 11:46
#152 was closed as a duplicate of this issue.  That's not exactly true as that issue was specific to having validation specified in a schema.

**Comment by mkmik** [comment] 2022-03-07 11:36
Currently we have a dummy schema in the `schema-v1alpha1.yaml` file:

```
openAPIV3Schema:
  type: object
  properties:
    spec:
      type: object
      x-kubernetes-preserve-unknown-fields: true
    status:
      x-kubernetes-preserve-unknown-fields: true
```

It's shared by the jsonnet and the helm templates.

**Comment by uberspot** [comment] 2022-06-27 15:15
Any suggestions in a way forward here (other than forking the schema)? Developers keep hitting issues because their sealed secret is missing e.g. the Type and even though unsealing works, the secret spec is wrong and never applies. 
Long-term this would be the best place to update the schema in ^ .

**Comment by snorwin** [comment] 2022-09-02 07:24
The approach suggested in #941 is to skip schema validation only for the `.spec.encryptedData` and at the same time skip parsing errors for the part without schema validation. I think this would increase the usability significantly and prevent issues like #505.

**Comment by mkmik** [comment] 2022-09-02 08:17
Can somebody TL;DR me why `x-kubernetes-preserve-unknown-fields: true` wouldn't work nowadays in the `encryptedData` sub-object?

**Comment by snorwin** [comment] 2022-09-02 08:22
@mkmik it will work and basically that's what I did in #941.

**Comment by mkmik** [comment] 2022-09-02 08:28
Awsome! will take a look there!

**Closed** 2022-09-09 09:14 UTC
Labels: bug, backlog
