### ISSUE TITLE
Helm chart has confusing information about CRDs

### ISSUE THREAD

**Issue by jonkerj** [bitnami-labs/sealed-secrets#514] opened 2021-01-27 08:58 UTC
First of all: thank you for moving the chart from helm/stable to bitnami!

Since 4cfc45b2 the helm chart does not install CRDs anymore. The values and README, however, suggest it does (`crd.create` and `crd.keep`). When people upgrade from pre-1.14.0 to 1.14.x (like I did), they lose the CRDs. 

I'd think the chart should either install/keep the CRDs, or the README should reflect the situation (upgrade instructions from pre-1.14.0, CRD install oneliner) and the crd-values should be removed. My guess is the latter is the preferred one, but I am not sure. If it helps, I could send in a PR to update the values/README.

**Comment by laszlocph** [comment] 2021-04-19 17:45
I also lost my CRDs upgrading from 1.10.3 to 1.15.0-r3.

But my other clusters who started with 1.15.0-r3 had CRDs, so I think the chart still installs them. Just as your linked commit suggests. The `crd.create` and `crd.keep` are not there anymore, that's true.

What I ended up doing was deleting the helm release, and recreating it on the latest version. Then recreates my sealed secrets from my gitops repo. But the behavior is odd, although I don't think the CRD update lifecycle is generally figured out by the community.

**Comment by jonkerj** [comment] 2022-01-31 09:11
bump

**Comment by rickard-von-essen** [comment] 2022-01-31 09:32
https://github.com/bitnami-labs/sealed-secrets/issues/600#issuecomment-1025539515

**Comment by juan131** [comment] 2022-02-03 15:19
Duplicate of https://github.com/bitnami-labs/sealed-secrets/issues/600

**Closed by juan131** 2022-02-03 15:19 UTC
