### ISSUE TITLE
Missing controller.yaml from assets of v0.17.0 release

### ISSUE THREAD

**Issue by ka-zsolt** [bitnami-labs/sealed-secrets#674] opened 2021-12-14 15:05 UTC
Hi!

As title says, I can't find controller.yaml at the assets section of the newest v0.17.0 release.
https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.17.0

> wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.0/controller.yaml                   ─╯
--2021-12-14 16:14:40--  https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.0/controller.yaml
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-12-14 16:14:40 ERROR 404: Not Found.

Might be related to #661 

Thanks!

**Comment by juan131** [comment] 2021-12-14 16:44
Duplicate of https://github.com/bitnami-labs/sealed-secrets/issues/674

**Closed by juan131** 2021-12-14 16:44 UTC
