### ISSUE TITLE
kubeseal --validate only validates the first secret

### ISSUE THREAD

**Issue by wojciechka** [bitnami-labs/sealed-secrets#474] opened 2020-11-09 10:48 UTC
When running `kubeseal --validate`, it validates only the first document and does not report an error when other documents cannot be unsealed - for example:

```
---
$ kubeseal --validate
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: valid
  namespace: default
spec:
  encryptedData:
    SECRET: <valid secret>
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: invalid
  namespace: default
spec:
  encryptedData:
    SECRET: <invalid secret>
````

Returns zero exit code.

I am not sure what the best way to do it is. I believe one option is the input should be parsed in the CLI and sent as multiple requests, perhaps only when a new flag like `--yaml-stream` is passed. Another option is to have the handler for `v1/verify` handle multiple YAML objects.

**Comment by mkmik** [comment] 2020-11-09 13:44
Duplicate of #114 ?

**Comment by wojciechka** [comment] 2020-11-09 13:49
> Duplicate of #114 ?

Yes and no. #114 is about sealing, mine is about validation only.

I suppose whether it's duplicate depends on implementation - making sealed-secrets support multiple documents as input and output would resolve this as well.

**Comment by mkmik** [comment] 2020-11-09 13:52
ok, mentioned `--validate` in #114; I think we can join these two tasks

**Closed by mkmik** 2020-11-09 13:52 UTC
