### ISSUE TITLE
Upgrade to 0.12.1 results in "no endpoints available for service"

### ISSUE THREAD

**Issue by acarsercan** [bitnami-labs/sealed-secrets#397] opened 2020-04-20 08:27 UTC
Hi,

Just upgraded from 0.9.1 to 0.12.1 using community Helm chart

Unfotunately I can't seem to fetch my certificate now
```
kubectl proxy
curl http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/http:sealed-secrets:/proxy/v1/cert.pem

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "no endpoints available for service \"http:sealed-secrets:\"",
  "reason": "ServiceUnavailable",
  "code": 503
```

Not sure what I've broken, all the objects seem to be there

```kubectl --namespace kube-system get po,svc,ep,rs,deploy -A | grep sealed-secrets
kube-system                     pod/sealed-secrets-bdb884ddb-vxf9f                                         1/1     Running     0          49m

kube-system                     service/sealed-secrets                                         ClusterIP      100.69.184.31    <none>                                                                          8080/TCP                                                                                                     152d

kube-system                     endpoints/sealed-secrets                                         100.96.21.145:8080                                                            152d

kube-system                     replicaset.extensions/sealed-secrets-66fd94bb9d                                         0         0         0       152d
kube-system                     replicaset.extensions/sealed-secrets-7b6f8778c9                                         0         0         0       152d
kube-system                     replicaset.extensions/sealed-secrets-bdb884ddb                                          1         1         1       49m

kube-system                     deployment.extensions/sealed-secrets                                         1/1     1            1           152d
```

Any help is appreciated

**Comment by mkmik** [comment] 2020-04-20 08:47
```
kubectl -n kube-system get pod -o wide -lname=sealed-secrets-controller
```

?

**Comment by acarsercan** [comment] 2020-04-20 09:39
Mine is actually called `sealed-secrets`

Got it working by specifying the port in the curl URL

```http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/http:sealed-secrets:8080/proxy/v1/cert.pem```

Looks like kubeseal binary isn't configured to do something similar?

**Comment by mkmik** [comment] 2020-04-20 09:44
If you rename the controller name, you need to pass a flag (or env var to kubeseal) to tell it the new name:

```
$ kubeseal --help

      --controller-name string           Name of sealed-secrets controller. (default "sealed-secrets-controller")
```


the env var is `SEALED_SECRETS_CONTROLLER_NAME`.

Keep in mind that the helm chart is not official and it's maintained by the community; I don't know if they changed the default of the service name there.

**Comment by acarsercan** [comment] 2020-04-20 09:51
Sorry I seemed to have caused confusion, I'm specifying the correct controller name, however its failing to find it as the port for the service seems not 8080? 

```
sealed-secrets                              ClusterIP   100.69.184.31    <none>        8080/TCP                 153d
```

So the following works:
```http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/http:sealed-secrets:8080/proxy/v1/cert.pem```

But you can't speciy the port in kubeseal binary as it adds extra `:` in the URL
```kubeseal --fetch-cert --controller-name=sealed-secrets:8080 > pub.cert
error: cannot fetch certificate: invalid service request "http:sealed-secrets:8080:"```

**Comment by mkmik** [comment] 2020-04-20 10:04
that's weird, kubeseal should be able to fetch the cert (i.e. it works for me and it's listening on port 8080 too)

What version of k8s are you running?

**Comment by mkmik** [comment] 2020-04-20 10:04
and also:

```
kubeseal --version
```

?

**Comment by acarsercan** [comment] 2020-04-20 10:10
I'm running kubernetes 1.14.9 and  kubeseal version: v0.12.1+dirty

I'm guessing the problem is the way Helm upgraded from 0.9 to 0.12

Like you said, this is a community chart, but I appreciate the replies.


________________________________

**Comment by mkmik** [comment] 2020-04-20 10:18
I'd love to troubleshoot this, regardless of where the chart comes from; I want to know why it fails :-)


When you upgraded from 0.9 to 0.12, was sealed-secrets the only thing you upgraded (or did you also upgrade k8s versions contextually?)

Can you downgrade to 0.9 and verify it works again?

Can you provide a diff of the yaml files of the actual svc resources between those two versions?

**Comment by mkmik** [comment] 2020-04-20 10:20
Another thing:

```sh
kubectl -n kube-system get pod sealed-secrets-bdb884ddb-vxf9f  -o yaml | grep ports: -A 4
```

**Comment by acarsercan** [comment] 2020-04-20 10:27
I see the same
```    
](master)$ kubectl -n kube-system get pod sealed-secrets-bdb884ddb-vxf9f  -o yaml | grep ports: -A 4
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    readinessProbe:
```

> I'd love to troubleshoot this, regardless of where the chart comes from; I want to know why it fails :-)
> 
> When you upgraded from 0.9 to 0.12, was sealed-secrets the only thing you upgraded (or did you also upgrade k8s versions contextually?)

Just sealed secrets by bumping the chart version from  version: 1.5.0 to 1.9.0

> Can you downgrade to 0.9 and verify it works again?
I will check
> Can you provide a diff of the yaml files of the actual svc resources between those two versions?
Nothing seems to have changed for a while?
https://github.com/helm/charts/blob/master/stable/sealed-secrets/templates/service-account.yaml

**Comment by achandras** [comment] 2020-04-20 22:03
Hi,

I'm also running into this issue. I am not very familiar in this area, but I believe it was caused by this recent change that named the service's port:
https://github.com/helm/charts/pull/21966/files#diff-822b8d1b504d8676f375fe2f01655d91R15

As @acarsercan mentioned, curling `sealed-secrets-controller:http` or `sealed-secrets-controller:8080` seems to work. Using the argument `--controller-name=sealed-secrets-controller:http`, when the url gets constructed in kubeseal (possibly due to how the k8s client-go lib builds the proxy url), an extra ":" gets added to the end.

Removing the named port in the [service](https://github.com/helm/charts/blob/master/stable/sealed-secrets/templates/service.yaml) seems to fix the problem for me entirely and kubeseal goes back to working without any issues.

Aside from this, being able to configure a port still seems like a useful feature. Would that be something you would consider supporting?

**Comment by mkmik** [comment] 2020-04-21 06:35
@achandras thanks!

This is the Service resource from the official released manifests (controller.yaml available from the /releases page):

```
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: sealed-secrets-controller
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    name: sealed-secrets-controller
  type: ClusterIP
```

**Comment by mkmik** [comment] 2020-04-21 06:40
> Aside from this, being able to configure a port still seems like a useful feature. Would that be something you would consider supporting?

@achandras I don't know, in which circumstance that is not a misconfiguration would this be useful?

I plan to do something about this helm chart. I do understand why people want helm (familiarity, etc), but I don't want helm to be the primary distribution mechanism.I don't want to get deeply into why I don't like helm, let's say it doesn't fit in this margin. That said I can no longer ignore the problem, the manifests are diverging and we're going to hit confusing bugs like this.

I'm considering supporting the helm chart officially, somehow (either by having a team at bitnami responsible for packaging this component, and taking all support requests, or by finding a way to machine generate a helm chart from the release yaml + some metadata)

**Comment by achandras** [comment] 2020-04-21 13:10
> @achandras I don't know, in which circumstance that is not a misconfiguration would this be useful?

@mkmik I had not considered it like that, and on further thought any possible scenario I can think of would certainly be a misconfig, especially given the official Service definition 🙂

**Comment by bmcustodio** [comment] 2020-04-24 08:00
The issue is caused by the fact that the Helm chart names the service's port (as `http`, instead of leaving the name empty), which conflicts with this [`ProxyGet` call](https://github.com/bitnami-labs/sealed-secrets/issues/397):

```
$ curl http://localhost:8001/api/v1/namespaces/sealed-secrets/services/http:sealed-secrets-controller:/proxy/healthz
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "no endpoints available for service \"http:sealed-secrets-controller:http\"",
  "reason": "ServiceUnavailable",
  "code": 503
}%
```

as opposed to

```
$ curl http://localhost:8001/api/v1/namespaces/sealed-secrets/services/http:sealed-secrets-controller:http/proxy/healthz
ok%
```

I think there are two options here:

1. Remove the port name from the Helm chart.
2. Add a fallback strategy to that function so that both named and unnamed ports work.

I can have a go at any if necessary.

**Comment by mkmik** [comment] 2020-04-24 08:01
Let's fix the helm chart to match the official manifest

**Comment by bmcustodio** [comment] 2020-04-24 08:12
@mkmik sure, https://github.com/helm/charts/pull/22097 is up for reviewing ;)

**Comment by evanreichard** [comment] 2020-04-29 04:02
I wonder if this is a kubernetes bug. In the API call you can change `http:service-name:` to `http:service-name:8080` or `service-name:http` and it will work.

And as per kubernetes documentation [0]:
```
https:<service_name>: - proxies to the default or unnamed port using https (note the trailing colon)
```
It appears that this is only true if it's unnamed, _not_ just the default. Unless I'm misunderstanding this.

[0] https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#manually-constructing-apiserver-proxy-urls

**Comment by mkmik** [comment] 2020-05-03 13:05
An updated helm chart has been merged in the community chart repository. Please reopen if that didn't solve the problem

**Closed by mkmik** 2020-05-03 13:05 UTC
Labels: troubleshoot
