### ISSUE TITLE
Stable Helm chart deprecated

### ISSUE THREAD

**Issue by laszlocph** [bitnami-labs/sealed-secrets#476] opened 2020-11-16 08:36 UTC
The linked stable Helm chart was deprecated in scope of the helm v2 -> v3 move.

Can you point me to the new official chart?

The official Helm chart repo after the migration does not contain the Sealed Secret Helm chart that used to be on this link:
https://github.com/helm/charts/tree/master/stable/sealed-secrets

**Comment by mkmik** [comment] 2020-11-16 10:07
duplicate of #389

**Closed by mkmik** 2020-11-16 10:07 UTC
