### ISSUE TITLE
Add OpenAPIV3Schema validation to the sealed-secret CRD

### ISSUE THREAD

**Issue by smoyer64** [bitnami-labs/sealed-secrets#152] opened 2019-04-03 15:55 UTC

**Comment by Jc2k** [comment] 2020-09-16 09:14
I've started to look at using kubeval to validate my manifests in CI before deployment, unfortuantely at the moment that means all my sealed secrets trigger warnings. It would be nice to be able to turn on this lint check for all my CRDs instances.

CRD's have moved out of beta and with v1 schemas are now mandatory.

https://kubernetes.io/blog/2019/06/20/crd-structural-schema/

**Comment by kruton** [comment] 2022-01-28 01:58
Also adding my vote here. Is there any guidance on how one might contribute the CRD for this?

**Comment by juan131** [comment] 2022-02-03 11:17
Closing as duplicate of https://github.com/bitnami-labs/sealed-secrets/issues/82

**Closed by juan131** 2022-02-03 11:17 UTC
