### ISSUE TITLE
Add kustomization.yaml file in release

### ISSUE THREAD

**Issue by nwalens** [bitnami-labs/sealed-secrets#340] opened 2020-01-02 22:41 UTC
In order to make it easy to install sealed-secrets with kustomize, it would be nice to have kustomization.yaml files available to use as remote bases.

**Comment by mkmik** [comment] 2020-01-03 08:21
Duplicate of #309 or do you propose an alternative approach?

**Comment by nwalens** [comment] 2020-01-03 08:33
@mkmik I don't know what runs during the release process but if it is the Makefile, I was thinking about adding a step that would generate a kustomize.yaml file that would then be made part of the release.

I have implemented an ugly test on top of that idea in https://github.com/nwalens/sealed-secrets/commit/909a142aa251f9e24fe6c8dc42f3acc1bcbaaa7e

**Comment by mkmik** [comment] 2020-01-03 08:53
So, the idea is to just include the kustomization file in the releases downloadables and have the user download them manually?

**Comment by nwalens** [comment] 2020-01-03 09:28
If we have the kustomization.yaml file in place, the user can use it as a remote base as described in https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

With a remote base, one could reference it and apply customisations as needed or just install it with kubectl as in _kubectl kustomize https://github.com/bitnami-labs/sealed-secrets.git//kustomize/install?ref=v0.9.6_

**Comment by mkmik** [comment] 2020-01-03 09:52
Ok then this is a duplicate of #309 because kustomize remote build works with checked in files in git and thus we need to change our release procedure to perform a commit with the next version encoded in a checked in file right before we perform a git tag.

Thanks for showing interest in this; I'll close this issue in favour of #309  and bump its priority.

**Closed by mkmik** 2020-01-03 09:52 UTC

**Comment by nwalens** [comment] 2020-01-03 10:15
Sure thing, and thangs for you time!
