### ISSUE TITLE
cosign complains "no maching signatures"

### ISSUE THREAD

**Issue by yrro** [bitnami-labs/sealed-secrets#1170] opened 2023-04-04 12:57 UTC
I've not used cosign before so maybe I'm doing it wrong.  I get:

```
$ COSIGN_REPOSITORY=ghcr.io/bitnami-labs/sealed-secrets-controller/signs ~/go/bin/cosign verify --key cosign.pub ghcr.io/bitnami-labs/sealed-secrets-controller:v0.20.2
Error: no matching signatures:
signature not found in transparency log
 signature not found in transparency log
main.go:69: error during command execution: no matching signatures:
signature not found in transparency log
 signature not found in transparency log
```

Is this telling me that the image is signed but that I'm using the wrong public key?

```
$ cat cosign.pub
# Downloaded from <https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.20.2/cosign.pub>
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEseWNtEaI73oDVgjfLzU4eQYHE11i
MzRSNs1TA+cTT/Lw70ckfCC/vHnOXKACF2dnhsZsNNj647p9mAiYNVl9ug==
-----END PUBLIC KEY-----
```

**Comment by agarcia-oss** [comment] 2023-04-05 06:45
Hi @yrro I can reproduce the error but only with cosign v2.0; It didn´t happen on the previous version of cosign. Just to confirm: you are using closing 2 locally, right?

**Comment by yrro** [comment] 2023-04-05 07:59
Yes, `cosign version` reports `GitVersion: v2.0.0`

This also happens if I build from their `main` branch (`GitVersion: v2.0.0-75-gc900e9ac`)

(I am trying to get stackrox to verify the signature on our mirror of the images, it too is complaining that it can't verify the signature against the public key - but it doesn't give me any more information than that, hence me trying to figure out how to use `cosign` manually to check if the problem is with the image or with stackrox)

**Comment by alemorcuq** [comment] 2023-04-12 07:08
Hi, @yrro. Cosign introduced breaking changes in release v2, so it can't verify artifacts that were signed using the previous v1. You are using Cosign correctly, but this image was signed using Cosign v1, thus the error you are getting.

**Comment by agarcia-oss** [comment] 2023-04-13 07:46
We can close the issue since the cosign version we're using for the upcoming release has been upgraded to v2.

**Closed by agarcia-oss** 2023-04-13 07:46 UTC
Labels: bug
