### ISSUE TITLE
avoid ingress version incompatible with 1.22

### ISSUE THREAD

**Issue by davidkarlsen** [bitnami-labs/sealed-secrets#654] opened 2021-10-27 17:51 UTC
ingresses.v1beta1.networking.k8s.io is dropped in k8s 1.22
can maybe use https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_capabilities.tpl#L73 to make the version dynamic?

**Comment by jpetazzo** [comment] 2021-11-04 06:14
This seems to be a duplicated of #639 and addressed in #641.

**Comment by alvneiayu** [comment] 2021-12-16 15:43
hi @davidkarlsen and @jpetazzo 

With our last chart release, this problem has been solved. Let us know if you have any problem.

Thanks a lot

**Comment by juan131** [comment] 2021-12-23 08:32
Closing as duplicate of #639

**Closed by juan131** 2021-12-23 08:32 UTC
Labels: bug

**Comment by davidkarlsen** [comment] 2021-12-23 10:57
> hi @davidkarlsen and @jpetazzo
> 
> With our last chart release, this problem has been solved. Could you give a try, please? Let us know if you have any problem.

Thanks, the ingress problem got solved, however this new on appeared:
https://github.com/bitnami-labs/sealed-secrets/issues/694

**Comment by jpetazzo** [comment] 2022-01-09 17:36
Same here, will follow up on #694 !
