### ISSUE TITLE
Unable to use kubeseal offline with public certificate

### ISSUE THREAD

**Issue by kastwey** [bitnami-labs/sealed-secrets#102] opened 2018-05-30 08:12 UTC
Hi,

I have a minikube kubernetes cluster.
I installed kubeseal and yaml necesary to use kubeseal.
From my local, I was able to download the certificate (kubeseal --fetch-cert >mycert.pem)
However, when I try to run kubeseal --cert mycert.pem < mysecret.json > encrypted.json in other machine which has not configured the minikube cluster, the kubeseal sais to me that it has not the right configuration file (it spect the .kube/* files to exists).
Would be posible to use kubeseal offline without kube configuration, only with the publick key and the secret json or yaml file?

Best regards,

Juanjo.

**Comment by anguslees** [comment] 2018-05-31 05:32
What you've described is definitely the intended use.  Unfortunately there's a bug, and we initialise the client-go kubernetes client, even though when we don't use it - and this initialisation fails without a ~/.kube/config present.

See #101 for a bare-minimum kubeconfig file (no user auth secrets!) that will allow you to proceed.

**Comment by anguslees** [comment] 2018-05-31 05:32
(Closing as a duplicate of #101, please followup there)

**Closed by anguslees** 2018-05-31 05:32 UTC
Labels: duplicate

**Comment by kastwey** [comment] 2018-06-04 08:08
Thanks so much for your reply!
