### ISSUE TITLE
upgrading to 0.8.0 makes container panic

### ISSUE THREAD

**Issue by davidkarlsen** [bitnami-labs/sealed-secrets#204] opened 2019-07-25 16:48 UTC
Upgraded to the 1.3.0 chart and get:
```
kubectl -n sealed-secrets logs sealed-secrets-7bf5545f7d-2xbpp 
2019/07/25 16:47:01 Starting sealed-secrets controller version: v0.8.0
2019/07/25 16:47:01 Searching for existing private keys
panic: secrets is forbidden: User "system:serviceaccount:sealed-secrets:sealed-secrets" cannot list resource "secrets" in API group "" in the namespace "sealed-secrets"

goroutine 1 [running]:
main.main()
        /home/travis/gopath/src/github.com/bitnami-labs/sealed-secrets/cmd/controller/main.go:218 +0x20a
```

**Comment by mkmik** [comment] 2019-07-25 16:54
Thanks for reporting, however the helm chart is maintained by the community.

It seems that the issue you report is the duplicate of https://github.com/helm/charts/issues/15837

**Closed** 2019-07-25 16:54 UTC

**Comment by davidkarlsen** [comment] 2019-07-25 22:24
Thanks - do you have some raw deployment descriptors updated for v0.8 for reference which we can use for the chart updates? TIA

**Comment by mkmik** [comment] 2019-07-26 05:41
Sure, they are attached to the release.
